### ISSUE TITLE
Cleave delimiter "." issue

### ISSUE THREAD

**Issue by adnan-zahir** [Curaweda-X-MBU/MBU-ERP#43]
## Description
If cleave initialize using delimiter option to be "." and decimal mark "," `1.000.000,00` instead of `1,000,000.00` would sometimes causes input elements to be bugged.

## Possible Problems
It can cause :
1. Input elements to have limit of input length (can't go past 3 numbers).
2. Fail to initialize numeral-mask.

## Temporary Solution
Change the options, using 'en-GB' format `1,000,000.00` for now.
- [x] Set cleave helper function accordingly.
- [x] Set parseLocale helper function accordingly.

## TODO
- [x] Make own helper function to replace cleave
